export interface Budget {
  id: string;
  title: string;
  amountPlanned: number;
  amountSpent: number;
  items: { id: string; name: string; amount: number, isCompleted: boolean }[];
  /** ISO-8601 period identifier, e.g. "2025-08" for August 2025 */
  period: string;
  /** Specific calendar date for this budget (YYYY-MM-DD) */
  dateISO?: string;
  /** Optional free-text category label */
  category?: string;
  /** Optional emoji or glyph representing the category */
  categoryIcon?: string;
  /** Optional recurring rule. Currently only 'monthly' or 'none' */
  recurring?: 'weekly' | 'monthly' | 'quarterly' | 'annually' | 'none';
  /** Anchor date (ISO yyyy-mm-dd) used to compute next recurring occurrence */
  anchorDateISO?: string;
  /** Optional stop date (inclusive) for recurring budgets (YYYY-MM-DD). When present and recurring != 'none', auto-generate occurrences until this date. */
  recurringStopISO?: string;
  /** Identifier to group all auto-generated occurrences of the same recurring budget */
  recurringGroupId?: string;
  /** True when an item was auto-generated from a recurring rule */
  isAutoGenerated?: boolean;
  notes?: string;
  createdAt: number; // epoch millis
  updatedAt: number; // epoch millis
}
